---
- name: install essential packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - openjdk-7-jre

- name: check if jenkins home directory exists
  stat: path=/var/lib/jenkins
  register: jenkins_home_directory

- name: install public key
  apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present
  when: jenkins_home_directory.stat.exists == false

- name: install repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  when: jenkins_home_directory.stat.exists == false

- name: install jenkins
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - jenkins

- name: create apache2 site
  template: src=vhost.conf dest=/etc/apache2/sites-available/100-ci-jenkins.conf
  notify:
    - ci_jenkins_apache2_restart

- name: enable apache2 site
  command: a2ensite 100-ci-jenkins.conf creates=/etc/apache2/sites-enabled/100-ci-jenkins.conf
  notify:
    - ci_jenkins_apache2_restart

- name: mount jenkins directory
  action: mount name=/var/lib/jenkins src={{ci_jenkins_mount_src}} fstype={{ci_jenkins_mount_type}} state=mounted
  when: ci_jenkins_mount_src != ""
  notify:
    - ci_jenkins_apache2_restart

- name: mount jenkins thin-backup
  action: mount name=/var/lib/jenkins-thin-backup src={{ci_jenkins_mount_backup_src}} fstype={{ci_jenkins_mount_backup_type}} state=mounted
  when: ci_jenkins_mount_backup_src != ""
  notify:
    - ci_jenkins_apache2_restart