---
- name: configure os
  set_fact:
    server_base_os: "{{ansible_distribution|lower}}{{ansible_distribution_major_version|int}}"

- name: include os variables
  include_vars: "{{server_base_os}}.yml"

# define os variables

- name: define ci_jenkins_java_package
  set_fact:
    ci_jenkins_java_package: "{{__ci_jenkins_java_package}}"
  when: ci_jenkins_java_package is not defined

- name: define ci_jenkins_command_jenkins_restart
  set_fact:
    ci_jenkins_command_jenkins_restart: "{{__ci_jenkins_command_jenkins_restart}}"
  when: ci_jenkins_command_jenkins_restart is not defined

- name: define ci_jenkins_command_apache2_restart
  set_fact:
    ci_jenkins_command_apache2_restart: "{{__ci_jenkins_command_apache2_restart}}"
  when: ci_jenkins_command_apache2_restart is not defined

# setup os

- name: setup {{server_base_os}}
  include: "{{server_base_os}}.yml"