---
- name: install {{ci_jenkins_java_package}}
  apt: pkg={{ci_jenkins_java_package}} state=present update_cache=yes cache_valid_time=3600

- name: check if jenkins home exists
  stat: path=/var/lib/jenkins
  register: ci_jenkins_home_directory

- name: install public key
  apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present
  when: ci_jenkins_home_directory.stat.exists == false

- name: install repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  when: ci_jenkins_home_directory.stat.exists == false

- name: install jenkins
  apt: pkg=jenkins state=present update_cache=yes cache_valid_time=3600

# proxy check

- name: check if apache2 exists
  stat: path=/etc/init.d/apache2
  register: ci_jenkins_apache2_exists

# proxy vhost

- name: enable apache2 proxy
  apache2_module: state=present name={{item}}
  with_items:
    - proxy
    - proxy_http
  notify:
    - ci_jenkins_apache2_restart
  when: ci_jenkins_apache2_exists.stat.exists == true

- name: create apache2 proxy vhost
  template: src=vhost.conf dest=/etc/apache2/sites-available/100-ci-jenkins.conf
  notify:
    - ci_jenkins_apache2_restart
  when: ci_jenkins_apache2_exists.stat.exists == true

- name: enable apache2 proxy vhost
  command: a2ensite 100-ci-jenkins.conf creates=/etc/apache2/sites-enabled/100-ci-jenkins.conf
  notify:
    - ci_jenkins_apache2_restart
  when: ci_jenkins_apache2_exists.stat.exists == true

# mounting

- name: mount jenkins directory
  action: mount name=/var/lib/jenkins src={{ci_jenkins_mount_src}} fstype={{ci_jenkins_mount_type}} state=mounted
  when: ci_jenkins_mount_src != ""
  notify:
    - ci_jenkins_jenkins_restart
    - ci_jenkins_apache2_restart

- name: mount jenkins thin-backup
  action: mount name=/var/lib/jenkins-thin-backup src={{ci_jenkins_mount_backup_src}} fstype={{ci_jenkins_mount_backup_type}} state=mounted
  when: ci_jenkins_mount_backup_src != ""
  notify:
    - ci_jenkins_jenkins_restart
    - ci_jenkins_apache2_restart